### ISSUE TITLE
Handle default inline mode styling better

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#108]
After seeing https://eager.io/blog/introducing-embedbox-open-source-embed-code-ui/ I did some hunting in the code and left this comment: https://github.com/EagerIO/EmbedBox/commit/a30955cfa7b01319381557e72fc9dfafb0af7479#commitcomment-18974686. Let’s think about this more broadly though.

**Comment by adamschwartz** [comment]
cc @TeffenEllis

**Comment by adamschwartz** [comment]
I also think the inline version kind of makes no sense on small screens, so I suggested to @zackbloom that in the blog post we display the inline one for our desktop breakpoint, and then show a button to launch a modal for our mobile breakpoint. But I’m wondering now if perhaps this should be something offered by the library itself? I suppose it would be pretty easy to implement on the blog without EmbedBox offering a more direct way to do this, but one potential advantage of having the library do it is handling the responsive switch (if someone resizes a browser) and applying a nice default styling (using the `accentColor`, e.g.) to the button we show to launch the modal on mobile.

**Comment by TeffenEllis** [comment]
Status update,

Master includes better default alignment and styles when in inline mode.

**Comment by adamschwartz** [comment]
https://github.com/EagerIO/EmbedBox/commit/977d8b75fda86a007996944c81f6e1d0e1ea328b
