### ISSUE TITLE
Capitalization consistency

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#110]
![image](https://cloud.githubusercontent.com/assets/154613/18482874/e4dbafba-79af-11e6-8aee-f82b6efd8491.png)

“Embed Code” vs. “Content slots”

**Comment by zackbloom** [comment]
One could argue the Embed Code is a proper noun while the other two aren't, but it would be a waste of time.  Make it consistent whichever way you prefer!

**Comment by adamschwartz** [comment]
That’s a good point. Perhaps it was a waste for me to even have made this issue then! 😎 

Here’s an example with Adobe using it phrase-case:
https://helpx.adobe.com/typekit/using/embed-codes.html

So I’ll go with that. 👍 

Thx
