### ISSUE TITLE
Link from landing page to readme/docs

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#13]

**Comment by TeffenEllis** [comment]
@adamschwartz I think an anchor down to the docs portion from the hero slide could be cool. What are your thoughts on the classic "fork me on github" corner strip or a star count? 

Perhaps something like this in the upper right hand corner?
```
Documentation | Github
```

**Comment by adamschwartz** [comment]
I’d probably go with the classic buttons/links under the logo and hero text:

A few options:

![image](https://cloud.githubusercontent.com/assets/154613/17375241/1eb69f80-597e-11e6-96e5-f51fd6e77a8f.png)

![image](https://cloud.githubusercontent.com/assets/154613/17374877/a05c6242-597c-11e6-9908-03d0c4674aa9.png)

![image](https://cloud.githubusercontent.com/assets/154613/17375084/91398140-597d-11e6-9466-e6e50be58f51.png)

**Comment by TeffenEllis** [comment]
I'm fond of the clean look of the first mockup. It's up on master :)

**Comment by adamschwartz** [comment]
Looks pretty solid. `:visited` colors could use a little love though:

![image](https://cloud.githubusercontent.com/assets/154613/17460234/0b7bee84-5c2b-11e6-8094-8b5fa29ee169.png)

**Comment by adamschwartz** [comment]
Took a pass: https://github.com/EagerIO/EmbedBox/commit/3255d9db04113ea6a1a9f93180a0e5ef528631b4

**Comment by TeffenEllis** [comment]
Nice! I've fleshed out some over styles, and `flex`'d the container a bit. Looks great on mobile!
