### ISSUE TITLE
Write docs for more targets

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#17]
Here is what I think we need at a minimum for launch:

- [x] Joomla
- [ ] Drupal
- [x] Wordpress
- [x] Weebly
- [ ] Shopify
- [x] Manual

**Comment by adamschwartz** [comment]
Also these?
- [ ] Wix
- [ ] Squarespace

**Comment by zackbloom** [comment]
While we're talking about this, I'll say that I've been using Skitch with arrows in the Eager brand color for screenshots.  I imagine we'll want to keep that consistent so speak now or forever hold your peace.

**Comment by zackbloom** [comment]
@TeffenEllis If you need help getting these written / screenshotted, get all the API / format / brand guidelines tee'd up and we can divide up the work.

**Comment by adamschwartz** [comment]
For v1 I think we should use a yellow/orange highlight color as it is IMHO the most universal:

![image](https://cloud.githubusercontent.com/assets/154613/17188274/5676d422-540a-11e6-9da4-2e8dcf5e7e84.png)

However long-term I think the best approach would be to commit the images sans-annotations and display SVG/HTML annotations on top of them such that annotation text is highly readable and annotation colors can be configurable. This can wait till v2 though unless @TeffenEllis is really excited about the idea. ;)

**Comment by adamschwartz** [comment]
This is consistent with our hint colors as well:

![image](https://cloud.githubusercontent.com/assets/154613/17188354/a6d865de-540a-11e6-8f40-43dc9ca8406f.png)
![image](https://cloud.githubusercontent.com/assets/154613/17188394/d4a94492-540a-11e6-8664-33f8ed478817.png)

**Comment by zackbloom** [comment]
Using HTML-based annotations is interesting, we would need to figure out how to keep the creation-overhead to a minimum.  Truthfully, the biggest problem I've ran into is the opposite: how do we make screenshots which don't presuppose anything about the tool being embedded? I almost wish we could make the screenshot 'images' little iframes styled like the original tools so we could show the embed code being inserted, for example.

**Comment by adamschwartz** [comment]
I think we could probably pull that off in v2. 👍 For now though I think we should go with fixed yellow highlights or simple HTML annotations re: https://github.com/EagerIO/EmbedBox/issues/17#issuecomment-235685162.

**Comment by TeffenEllis** [comment]
I've updated the API with Zack's recommended flow. The target pages now have a much simpler markup which will make our task easier, and PRs less daunting :)

The markup simplification gave me a chance to touch up both cases of a `downloadURL` and `embedCode` config options. Feedback is appreciated 🐳 

I drew a blank on Drupal's instructions. Even after installing it myself it seems to be a tricky task of editing a theme file _somewhere_ 👻 

I'll have the skeleton up for the request targets, we can divide an conquer!

**Comment by adamschwartz** [comment]
Docs for creating new targets:
https://github.com/EagerIO/EmbedBox/blob/master/docs/new-targets.md

**Comment by TeffenEllis** [comment]
I'm closing this in favor of the target specific issues 😃
