### ISSUE TITLE
Show an example of modal usage in landing page or docs

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#18]

**Comment by adamschwartz** [comment]
@TeffenEllis if you just stick a button on the site which launches a modal, say in between the hero and features sections, I’ll style a nice section around that.

**Comment by TeffenEllis** [comment]
@adamschwartz,
I've implemented a fullscreen button on the floating modal. It's a bit odd given our iframe in iframe inception, but it does the job.

Let me know what you think 😄

**Comment by adamschwartz** [comment]
I’m seeing the overlay as cutoff:

![image](https://cloud.githubusercontent.com/assets/154613/17460153/5bb3360e-5c27-11e6-8383-ffce9970a682.png)

Also, to avoid confusion with EmbedBox itself, I feel like maybe this should be implemented as a two separate run buttons in the code block, something like this:

![image](https://cloud.githubusercontent.com/assets/154613/17460172/e9ecc2e6-5c27-11e6-9d27-0888326267cb.png)

**Comment by TeffenEllis** [comment]
@adamschwartz, fantastic idea!

I've implemented the buttons, and container docs. Having the EmbedBox in a container other than the body will create the element in inline mode. In this mode the close button and fade-in are disabled for instant appearance and permanence. 

The floating frame now takes advantage of this mode and removes our need for the iframe inception. The automated demo still uses an iframe to prevent input focus stealing, and to show off the "modal" UI with close buttons.

I'm going to mark this as resolved, but please open it again if you think something big is missing 🐳

**Comment by adamschwartz** [comment]
Thanks!

👍 Sick.
