### ISSUE TITLE
Stop embedbox.io animation if the user interacts with the demo

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#19]
This should also help with the weird glitches
![2016-07-27 at 2 04 pm](https://cloud.githubusercontent.com/assets/55347/17186586/d6bef0c6-5403-11e6-86be-eb7acaca4677.gif)

**Comment by adamschwartz** [comment]
Maybe even just on hover?

**Comment by zackbloom** [comment]
Maybe pause on hover, stop on click/focus.
