### ISSUE TITLE
Add embedbox.io to Typekit account

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#23]

**Comment by adamschwartz** [comment]
Why?

**Comment by zackbloom** [comment]
The page was showing a console error for me.

**Comment by adamschwartz** [comment]
Oh I see. We don’t actually use any Typekit typefaces so that can be removed. Avenir Next is currently the typeface of EmbedBox. @TeffenEllis I assume you added it before we landed on Avenir?

**Comment by TeffenEllis** [comment]
I believe all the TypeKit code is vestigial. We can remove it if Avenir Next is common enough 😄

**Comment by adamschwartz** [comment]
To my knowledge, TypeKit doesn’t offer Avenir Next. https://typekit.com/search/fonts?query=avenir
