### ISSUE TITLE
Don't let the user x out of box if it's not in a modal

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#24]
Right now you can on the landing page, leaving a blank box:
![image](https://cloud.githubusercontent.com/assets/55347/17187359/e3cf1bda-5406-11e6-9587-3e60fc6eea17.png)

**Comment by adamschwartz** [comment]
Also, when the page loads, it can sit like this for a bit. We should add some sort of loading animation to prevent this.

**Comment by adamschwartz** [comment]
Closed by accident.

**Comment by TeffenEllis** [comment]
Added a loading animation. The demo modal will reopen themselves after a short delay.

**Comment by adamschwartz** [comment]
👍
