### ISSUE TITLE
Decide on and document guidelines for creating images for docs

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#25]
Particularly how images should be cropped and what styles to use for overlay arrows/boxes/text.

Potentially we could provide assets (SVG arrows and boxes, e.g.) within the repo for annotating images in a uniform way.

This will go along way to the docs looking polished which I believe will be important for adoption and continued usage.

**Comment by adamschwartz** [comment]
cc @zackbloom @TeffenEllis

**Comment by TeffenEllis** [comment]
@adamschwartz,

This may have come up in a previous discussion. What are your thoughts on using full SVGs as screenshots? They're smaller in size and can reduced the information to it's core idea. The disadvantage would be the time to build them. Perhaps version 2?

**Comment by zackbloom** [comment]
Just to include the options, another is to grab the HTML from the site we are 'screenshotting', and reproducing it in an iframe.

**Comment by adamschwartz** [comment]
At the moment I’m partial to the idea of using static images (with bitmaps or SVGs as @TeffenEllis suggested) _with_ HTML or SVG overlaps, positioned with `%`, just as the pink dots work on http://eager.io and http://eager.io/for-websites.

![image](https://cloud.githubusercontent.com/assets/154613/17460207/feeaf526-5c29-11e6-922f-9e97a4e280be.png)

**Comment by adamschwartz** [comment]
Here are some annotation styles I’m working on for the docs.

<img width="511" src="https://cloud.githubusercontent.com/assets/154613/17502395/74598930-5db5-11e6-95eb-f48e342e5c06.png">

**Comment by adamschwartz** [comment]
https://github.com/EagerIO/EmbedBox/commit/4ffbee14498ab22a22f59aea617f0c4f4a53894d

**Comment by TeffenEllis** [comment]
@adamschwartz,

The Drupal target uses our much anticipated dynamic HTML/CSS screenshots, cutting file size significantly! 🐳

Dynamic screenshots are somewhat laborious to create but offer a great deal of customization. Smaller viewports can even take advantage of media queries to busy examples.

I've had some mixed results with consistent alignment of the curved SVG arrows across Chrome, Firefox, Safari, and IE10+
In the meantime I've made use of similarly styled unicode arrows and focal point "glow" class. They allow for a more precise alignment across reflows and keep things simple-ish. I think we can eventually replace unicode arrows with a more defined custom web font.

I'd like to close this issue but am open more discussion if you believe our current implementation should be improved before the release of 1.0

Cheers!
