### ISSUE TITLE
Potentially redesign the target search area and placeholder text message

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#44]
Lately I’ve been finding the search placeholder text kind of awkward. “Select or search...”, “Press or enter...”

I think that area might benefit from a design change in which there is an instruction above the search field, and then the search field had a placeholder which just read “Filter...” or “Search...”.

(@TeffenEllis I think this can wait until v2, but just wanted to get my thoughts out while I had them.)

**Comment by adamschwartz** [comment]
If you want this for v1.0.0 I’ll work on a mock! 👍

**Comment by TeffenEllis** [comment]
@adamschwartz this is a wishful 1.0.0 feature 😃 
Mocks appreciated!

**Comment by adamschwartz** [comment]
K

**Comment by adamschwartz** [comment]
<img src="https://cloud.githubusercontent.com/assets/154613/17759545/d15b615a-64c5-11e6-9022-e88672d6d77f.png" width="456">

**Comment by adamschwartz** [comment]
👍
