### ISSUE TITLE
Notion of embed-code-only targets

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#55]
@TeffenEllis maybe this is already a thing and I just don’t know how it works, but I think we need a way of saying a target only supports an embed code, and has no plugin system. I suppose we might also want the opposite, but in practice I don’t think that’s very common.

The idea then would be that once an embed code were provided in the configuration, we would either error and/[or (silently)] hide the plugin from the list of targets.

**Comment by TeffenEllis** [comment]
@adamschwartz,

I've added a few checks during target creation that validate whether or not rendering is possible with the given options. Internally targets have a policy on whether they're built for [plugins, embed codes, or both.](https://github.com/EagerIO/EmbedBox/blob/master/app/components/base-target/index.js#L35-L50) 

This is documented now too! http://embedbox.io/#downloads

Let me know if there's any gaps in the render logic 🐳 
Cheers
