### ISSUE TITLE
Flesh out hero copy / add logo

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#65]
@TeffenEllis 

![embedbox-site-changes-current-logo](https://cloud.githubusercontent.com/assets/154613/17834093/c7a73c60-66ff-11e6-9185-7e76c9bb12a6.png)

With a different logo concept (based on feedback from @zackbloom that the current one looks like a hexagon):

![image](https://cloud.githubusercontent.com/assets/154613/17834090/a6f809ae-66ff-11e6-8415-1afca7b5c543.png)

**Comment by TeffenEllis** [comment]
@adamschwartz,

I love the new logo!

I feel that the headline copy needs a bit of adjustment. Something like to make it less wordy hit harder.

Cheers

**Comment by renandincer** [comment]
I do like the new logo but I think it would look cooler with the eager pink+purple instead of the blue. I love the simple box like look.

**Comment by zackbloom** [comment]
That logo is :fire:

**Comment by adamschwartz** [comment]
Thanks everybody!

@renandincer I’ll try it both ways, thanks for the suggestin.

@TeffenEllis I’ll put the new logo in `/media` and let you and @zackbloom flesh out the copy / layout changes.

**Comment by adamschwartz** [comment]
`logo-alt` added [media/logo-alt.png@0d9626](https://github.com/EagerIO/EmbedBox/blob/0d96264346e2fe614ebae2535de4530ea260639c/media/logo-alt.png)

<img width=300 src=https://cloud.githubusercontent.com/assets/154613/17910246/07beb942-6956-11e6-8b5b-87184fb8421b.png>

**Comment by TeffenEllis** [comment]
New logo and Adam's copy implemented!

Take it to the endzone, @zackbloom! 🏈

**Comment by adamschwartz** [comment]
This is live.
