### ISSUE TITLE
Regression: Enter no longer submits target list selection when search input is blurred

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#66]
Repro:
1. Visit http://embedbox.io
2. Click into demo.
3. Click WordPress.
4. Hit Enter.

**Comment by TeffenEllis** [comment]
@adamschwartz,

This was introduced in the accessibility changes. https://github.com/EagerIO/EmbedBox/commit/00781037979a6e38e87e530faedbbdf012ae60d1#diff-219ac9083f78b0aa72db25c0306c5af1R168

The input field uses the arrow keys to select targets, then enter navigates to the target instructions 

In the tab key flow, tabbing focuses through each targets. Then enter or spacebar is used to select an entry. The user must tab down to the "Next" button to navigate.

I believe limiting selection to the spacebar can make both concepts align to the user's expectations.

Thoughts?

**Comment by adamschwartz** [comment]
I liked the speed of it the other way, but this argument makes sense to me. I’ll leave it up to you! 👍
