### ISSUE TITLE
Drupal 8 instructions don’t support inserting embed into the head

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#68]
The key issue is it's really not easy for an end user to manually insert an embed code into the head of a Drupal site.  For Drupal 7 we instruct them to install an Add to Head module, but even that is not compatible with Drupal 8.  On Joomla they have to edit their theme, but at least it provides an editor inside the admin interface.  The only thing we could reasonably tell a Drupal user would be 'figure out where your files are stored, find the right theme, and edit the right template or php file'.

The absolute best option might be to make it so we could take an embed code and package up a quick Drupal 8 plugin the user could just install.  Of course, that's kinda what we're already doing with Eager, so perhaps the solution is to just tell developers to use that.

**Comment by TeffenEllis** [comment]
@zackbloom, @adamschwartz 

We could extend the [`supports`](http://embedbox.io/#pluginurl) attribute to signify if a target supports `insertInHead`.

Thoughts?

**Comment by adamschwartz** [comment]
wfm

**Comment by zackbloom** [comment]
Yea, it might be better in the long run to do like `insertInto: ['body']`.
