### ISSUE TITLE
improve shopify icon

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#69]
<img width=270 src=https://cloud.githubusercontent.com/assets/154613/18071957/cfdc0cf6-6e27-11e6-90c6-fb021ee7a443.png>

**Comment by adamschwartz** [comment]
![image](https://cloud.githubusercontent.com/assets/154613/18072458/7bcf27a6-6e2c-11e6-89fa-9c307ad49c3a.png)

**Comment by renandincer** [comment]
Looks incredibly pretty

**Comment by adamschwartz** [comment]
ty!
