### ISSUE TITLE
How are we handling wide screenshots?

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#7]
![image](https://cloud.githubusercontent.com/assets/55347/17186066/adc6542c-5401-11e6-9acb-684cc2ca6aa2.png)

Do we need a width max? Or the ability to click on them and have them expand? Or a wider embed?

**Comment by adamschwartz** [comment]
I thought about potentially implementing a fullscreen/maximize button next to the close × which would resize the entire modal to fit the window. This, coupled with Medium-style image styles which make grow images wider than the content column might be enough for what you’re trying to achieve here.

That being said, we want this to be responsive and be usable on iPads or other small screens, so we should probably strive for screenshots which are cropped well or use magnification within them to show the relevant details.

**Comment by adamschwartz** [comment]
Also where did you find that example?

**Comment by adamschwartz** [comment]
Wait never mind I see it’s in the `copy` branch.

**Comment by adamschwartz** [comment]
Just to provide one example, the following image from https://github.com/EagerIO/EmbedBox/pull/4/commits/9bdefa368e6908143055186a4bdf51d147e89c85:
![image](https://cloud.githubusercontent.com/assets/154613/17187481/632914b2-5407-11e6-94f4-05acafad8f73.png)

Could easily be cropped to:
![image](https://cloud.githubusercontent.com/assets/154613/17187474/5d264a30-5407-11e6-8be9-67dc496a5419.png)

**Comment by adamschwartz** [comment]
Additionally we could show images wider within the content space.

**Comment by adamschwartz** [comment]
e.g. Adding the following CSS:

```CSS
.markdown figure {
  margin: 1.5em -2em 2em -4em
}
```

Would yield this transformation:

<img width=256 src=https://cloud.githubusercontent.com/assets/154613/17187636/1d576f5a-5408-11e6-899b-a8b3ef8836d8.png>
<img width=256 src=https://cloud.githubusercontent.com/assets/154613/17187631/1a85c344-5408-11e6-9b31-454a4bc56b34.png>

**Comment by TeffenEllis** [comment]
Implemented full width figure images as described above. Thoughts?

**Comment by adamschwartz** [comment]
Seems fine to me, especially as a trial. If we do keep it as the “final” v1 design though we should probably eventually implement it as pulling in the margins on non-figure elements rather than using negative margins on the figures.
