### ISSUE TITLE
Add color options for step numbers and screenshot annotations (arrows, outlines)

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#70]
Currently there are three color options for the theme:

```ES6
static theme = {
  accentColor: "#2d88f3",
  backgroundColor: "#ffffff",
  textColor: "#000000"
};
```

Per our discussion today:

- There will be two additional color options, something like `stepNumberColor` and `screenshotAnnotationColor`.
- By default, `stepNumberColor` will default to `accentColor`.
- By default, `screenshotAnnotationColor` will default to `#fde757`, currently defined as `attentionYellow` in the Stylus.

By _not_ defaulting the `screenshotAnnotationColor` color to the `accentColor`, as we do with the `stepNumberColor`, we can avoid the surprise of a developer ending up with a poor color for the annotation arrows. However, if a particular accent color works well as an annotation color, as with the purple and green designs below, a developer would be able to achieve these by setting the `accentColor`, `stepNumberColor` and `screenshotAnnotationColor` to the same hex value.

<img src=https://cloud.githubusercontent.com/assets/154613/18078843/a7190358-6e5b-11e6-8038-8d5c555fc20d.png>

**Comment by adamschwartz** [comment]
Another example of what’s possible re: https://github.com/EagerIO/EmbedBox/commit/97415f287544b8cd902e4f65e3e09c646dd9297c:

![image](https://cloud.githubusercontent.com/assets/154613/18078843/a7190358-6e5b-11e6-8038-8d5c555fc20d.png)

**Comment by adamschwartz** [comment]
cc @zackbloom @TeffenEllis

**Comment by TeffenEllis** [comment]
@adamschwartz,

I like the color feature quite a bit! 

It's longterm goal to replace all the PNGs with iframe screenshots. The iframe screenshots are slightly different on smaller screens and have new line heights when content wraps. The absolute positioning of the arrow may be off in this case. 

IE10 is especially touchy with SVG viewboxes and horizontal scrolling. I believe the arrow that is aligned is imprinted the PNG. The misaligned one is the SVG.

<img width="602" alt="screen shot 2016-08-30 at 12 02 13 am" src="https://cloud.githubusercontent.com/assets/592134/18079431/8147f4b0-6e45-11e6-8196-d22de1c10a74.png">


The current feature we have with inline pseudo element arrows will fit any screen width. My feeling is that they're the best option along with occasionally highlighting key elements.

At the moment these pseudo elements are set with unicode arrows. Replacing them data URI SVGs with the size could get us the prettiness of a custom arrow, and the simplicity of our current system.

Cheers

**Comment by adamschwartz** [comment]
I’ll see what I can do about IE.

As for horizontal scrolling, I would guess that’s a separate issue?

Lastly, the implementation is not of primary concern to me (inline SVG vs. SVG data URI in CSS), however, I want to note that I am not satisfied with the existing unicode arrows because IMHO they blend into the content much more easily. I designed these arrows intentionally curvy because the way they gesture is more attention grabbing as it breaks the horizontality/verticality of a typical web UI.

I’m willing to be convinced otherwise, but for now, I’d like to implement the HTML screenshots in such a way that they scale as images do, retaining their exact layout, such that their behavior mimics an actually screenshot. This will double as solving the arrow positioning issue for us.

Back to implementation. As I said it’s a secondary concern of mine. That being said I think you may find it annoying to implement the [`annotation-arrow` mixin](https://github.com/EagerIO/EmbedBox/commit/97415f287544b8cd902e4f65e3e09c646dd9297c#diff-a29e5d37c0ae8ab33318439786b47c36R38) with string interpolation inside Stylus.

**Comment by adamschwartz** [comment]
@TeffenEllis updated the description per our discussion today. 😄 

https://github.com/EagerIO/EmbedBox/issues/70#issue-173932250

**Comment by adamschwartz** [comment]
@TeffenEllis as part of this, I assume you’ll have to touch the `.screenshot .focal-point` styling. After playing around with that a bit I’d like to remove the [blur](https://github.com/EagerIO/EmbedBox/blob/015a2c6846df1c15ad357b27e446223531a475f9/app/components/base-screenshot/screenshot-iframe.styl#L30) on that and go with something more like this:

```stylus
.screenshot
  //...

  .focal-point
    box-shadow 0 0 0 4px attentionYellow
```

**Comment by TeffenEllis** [comment]
Sounds good to me 😄

**Comment by adamschwartz** [comment]
Thanks! 👍
