### ISSUE TITLE
Force iOS Safari bar to show on navigation into target

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#77]
When navigating into a target, if the iOS Safari bottom toolbar is visible, then the bottom of the instructions are unreadable. Scrolling the instructions doesn’t cause the bottom toolbar to fade away presumably because that scrolling is not taking propagated up. The only way I’ve found to get the toolbar to hide (and thus reveal the bottom of the instructions) is to attempt to drag up on the modal header. This is certainly annoying and non-obvious so we should figure out a solution. My proposition here is to force the bar to show somehow. Alternatively if we cannot do that we can place some reserved space below the scrolling area.

cc @TeffenEllis

**Comment by TeffenEllis** [comment]
Resolved in a5d4759 with additional padding in scrollable elements.
