### ISSUE TITLE
Modal header cropped in iOS Safari when entering target instructions

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#80]
I’m guessing this is due to the new positioning _not-_`fixed` stuff re https://github.com/EagerIO/EmbedBox/commit/a5d47599072bce5e225c4480fca6892a25a68f08. (Or maybe it’s the font size? I don’t think it’s the font size though cuz I’m not seeing the same issue in the desktop Chrome device simulator.)

<img width=640 src=https://cloud.githubusercontent.com/assets/154613/18156550/fcbd9cee-6fe4-11e6-8ca1-a4fead229cfc.png>

You can also tell since the `close.svg` isn’t vertically centered within the header.

cc @TeffenEllis

**Comment by TeffenEllis** [comment]
@adamschwartz,

This has something to do with Safari's calculation of viewport units on the iframe and the inner contents changing height. 
I'm 90% sure this is now fixed with ef692a285463a3f2db555b9be347ae062ceec7e2 \*crosses fingers\*

**Comment by adamschwartz** [comment]
Looks good to me!!! 👍
