### ISSUE TITLE
Remove target search selection flicker on iOS

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#87]
When you tap a target entry, the background turns blue, then grey, then blue again, rapidly.

**Comment by TeffenEllis** [comment]
I suspect this is something do the tabindex styles (both implicit and explicit)

**Comment by adamschwartz** [comment]
I think it’s `:active` →  `:focus` → `[data-selected]`.

**Comment by adamschwartz** [comment]
I think it’s `:active` →  `:focus` → `[data-selected]`, so I may just style `:focus` as blue on touch-devices.

**Comment by adamschwartz** [comment]
Turns out it was `:active` →  `:hover` → `[data-selected]`.
