### ISSUE TITLE
Deal with multiple versions of CMS

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#9]
Many CMS' have very different instructions based on which version you're dealing with.  One option would be to have separate entries for Drupal 7 & Drupal 8 for example.  Another would be to show a small '7 & 8' next to the entry for Drupal, and let the user choose which they want after clicking through.

**Comment by adamschwartz** [comment]
I think I’d like to implement this as a chooser (e.g. `<select>`) at the tope of the doc page for a CMS type. Something like this:

<img width=300 src=https://cloud.githubusercontent.com/assets/154613/17186746/75eabde2-5404-11e6-959f-342491f57ac7.png>

**Comment by zackbloom** [comment]
That works for me.  The one case I would make for instead doing it as a 'step' is the user could easily miss that dropdown and be confused why the instructions don't make any sense.  Forcing them to choose which version they have would limit that.

**Comment by adamschwartz** [comment]
If you feel strongly about that then my recommendation for implementation would be an interstitial page like the first one with a list view of the versions. (Obviously hideable/skippable/configurable though.)

![image](https://cloud.githubusercontent.com/assets/154613/17187984/61a3a998-5409-11e6-9c7d-ca5d71620ffe.png)

**Comment by zackbloom** [comment]
What would I'm not sure show?

**Comment by adamschwartz** [comment]
I meant to imply that the list of versions and their label text is configurable through the API. So e.g. a developer could add such an item to the versions list to show a special doc which attempts to guide the person first through figuring out what version they have. Like: “Try doing _____. If that works then you are are running Joomla Version 5. Click here to view the docs for Joomla Version 5. If that doesn’t work, try ______. If that works you are running an early version of Joomla not supported....”

**Comment by zackbloom** [comment]
Sure, my question was what would we do as a part of v1? Just put Drupal 7 & Drupal 8 in there, or are we gonna try to popular an I'm not sure page as well?

**Comment by adamschwartz** [comment]
Ahh gotcha. I think it would certainly be a nice example in the docs.

I do worry that making an interstitial page with just “Drupal 7” and “Drupal 8” in there might cause people to pause a bit. So perhaps we could have some text above the list (in place of where the search input is on the initial types page) which says something like: “Select your version of Drupal below. If you’re not sure which version you have, you can check it [here](https://www.drupal.org/node/139617).” (We can probably find a better link than that but hopefully you get the idea.

**Comment by adamschwartz** [comment]
Alternatively maybe we could go with the `<select>` idea I had above, but make the choice really juicy, perhaps two tiles which have small depictions of a differentiating piece of admin UI.

**Comment by adamschwartz** [comment]
I’m fine with either of the options I suggested above. I think this is something which we can expect to evolve as we build out support for many CMSs/versions.

**Comment by TeffenEllis** [comment]
@adamschwartz, @zackbloom 
 
I like the dropdown approach more since many users will either use a recent version or not know what version they have. 

A design like Adam's https://github.com/EagerIO/EmbedBox/issues/9#issuecomment-235672349 with slimmed down to "Version 1.2.3" with a "Help" link adjacent seems like a good fit to me :)

Thoughts?

**Comment by zackbloom** [comment]
> many users will either use a recent version

Sadly not really true: https://www.drupal.org/project/usage/drupal

> not know what version they have

Doesn't that mean they're just gonna get instructions they don't understand which don't work for them? Is that the solution?

**Comment by adamschwartz** [comment]
@TeffenEllis what don’t u like about this option?

![image](https://cloud.githubusercontent.com/assets/154613/17187984/61a3a998-5409-11e6-9c7d-ca5d71620ffe.png)

(From https://github.com/EagerIO/EmbedBox/issues/9#issuecomment-235682709)

**Comment by TeffenEllis** [comment]
@zackbloom, @adamschwartz,

I don't believe that CMS versions will differ so much that plugin installation and pasting embed codes require knowledge of version specific instructions. 

It's possible a user may have an outdated or even more recent version of the CMS and our screenshots will not match. It's also possible that the user may give up when confronted with the question.

>Select a Joomla version.

Likely response,
>_"I'm not sure how to do that... this is hard..." \*bounce\*_

Possible response,
>_I'll pick one at random._
>The user was lucky, or the instructions were similar enough that it didn't matter.

Possible response,
>_\*clicks "I'm not sure"\*_
>The user reads our instructions on how to find the version.

>They give up, or get confused along the way and give up.

>They find the version, come back and navigate back to the version select page, then to the version specific embed instructions. They still need to complete the original task at this point.

Every additional step the user takes is a potential for them to give up or get lost. Showing the user a recent version has fewer risks and is likely to fit their flow.

**Comment by adamschwartz** [comment]
Excellent points. Then let’s just come up with a solid design that gives enough prominence to the version selection that it is unlikely to be missed. I’ll think on this and post a mock back. In the meantime, the mock above with the `<select>` is a good start.

**Comment by adamschwartz** [comment]
Mock posted https://github.com/EagerIO/EmbedBox/pull/34

![image](https://cloud.githubusercontent.com/assets/154613/17537041/70e7720a-5e67-11e6-95d1-c0e44d714e6c.png)

**Comment by TeffenEllis** [comment]
Introduced in v0.0.11
