### ISSUE TITLE
Tabbing through content can lead to weird horizontal scrolling bugs

### ISSUE THREAD

**Issue by adamschwartz** [EagerIO/EmbedBox#90]
Due to the new transition implementation

![image](https://cloud.githubusercontent.com/assets/154613/18294401/e240cf7c-7466-11e6-9d4f-898dbc7cd8d7.png)

Probably all we need to do is apply something like `pointer-events none` to the inactive route.

**Comment by TeffenEllis** [comment]
Resolved with 2593f810913dcdc973802ebfa56ecbe201408cf0

**Comment by adamschwartz** [comment]
💯 awesome job
