### ISSUE TITLE
Improve code “Copy” button styling

### ISSUE THREAD

**Issue by zackbloom** [EagerIO/EmbedBox#97]
The idea is to make it look better given how we align the copyable text with the left edge of the page, not the rest of the text:

![image](https://cloud.githubusercontent.com/assets/55347/18360860/ba4f5688-75cd-11e6-99d0-58527a2fffe3.png)

I also like this more because it raises the weight of the copy button, which is the only real interaction anyone needs to have with the content.

**Comment by adamschwartz** [comment]
Thanks!

**Comment by adamschwartz** [comment]
@zackbloom I def do like the direction of this, but what should we do about multiline embed codes. Perhaps this should just be an optimization for single-line embed codes?

Here’s what this looks like with Disqus’s embed (with their comments _removed_, it’s usually even longer):
![image](https://cloud.githubusercontent.com/assets/154613/18370564/117fd51c-75fc-11e6-8d9c-c9f69d3040f4.png)

We could just display any embed code on one line but I feel like there’s some value in having people actually see the bulk of it. Anyhow, curious your thoughts.

**Comment by zackbloom** [comment]
Honestly, this looks fine to me: ![image](https://cloud.githubusercontent.com/assets/55347/18405539/bce1bad2-76c0-11e6-8871-e5453dcc575b.png)

**Comment by adamschwartz** [comment]
Went with a similar style to the run buttons in the site docs. Closed with https://github.com/EagerIO/EmbedBox/commit/e53ac5abdd8176c00f95e3cc04e24a4f5419ab92.

**Comment by zackbloom** [comment]
🚀

On Sep 9, 2016, at 7:32 PM, Adam Schwartz <notifications@github.com> wrote:

Went with a similar style to the run buttons in the site docs. Closed with
e53ac5a
<https://github.com/EagerIO/EmbedBox/commit/e53ac5abdd8176c00f95e3cc04e24a4f5419ab92>
.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/EagerIO/EmbedBox/issues/97#issuecomment-246068403>, or mute
the thread
